### ISSUE TITLE
Have students build their own ORM?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-defining-object-relational-mapping#1]
### Canvas Link

https://learning.flatironschool.com/courses/6049/pages/defining-object-relational-mapping?module_item_id=468021

### Concern

This is just a thought, but have we considered having students write their own ORMs for phase 3 without introducing a pre-built ORM like SQL alchemy? They would still learn about existing ORM frameworks in Phase 4, and this would give them more familiarity and confidence with what is actually happening in SQL alchemy. As it is currently, the section on understanding basic ORMs often gets breezed over by students, or at least isn't very well retained, since they don't need to use it for code challenge or project. This is a broader conversation, and I understand we're already rolling with SQLAlchemy for phase 3, but I think something like this could be beneficial.

**Comment by professor-ben** [comment]
Hey Matt,

I'm really glad you brought this up. This was something I suggested internally, but as you've observed, the existing "build-your-own-ORM" lessons are not very robust and would require pretty intense rewrites/additions. For the sake of time / pace of the Python project, we're going with this brief intro to Python with SQL and focusing more on the SQLAlchemy ORM. We also discussed the value in separating non-web development (P3) from web development (P4), but we'll see what the actual distribution of work is there. (Flask-SQLAlchemy also has some notable differences from vanilla SQLAlchemy...but maybe I'm rambling a bit at this point.)

I think that this is a smart direction for us to head in for future versions of the curriculum, though there's still going to be some debate as to whether or not it's the right one. I think that this is something we'll discuss further after the last build is released.

Thanks!
Ben
